# 📊 Marketing Campaign Performance Analytics

## Data Understanding

### Project Overview
This notebook focuses on understanding the marketing campaign dataset before any preprocessing or analysis. The objective is to explore the dataset's structure, identify data types, inspect missing values, detect duplicates, and gain initial insights that will guide the data cleaning and feature engineering stages.

### Objectives
- Load the dataset into Python
- Understand the dataset structure
- Examine columns and data types
- Identify missing values and duplicates
- Generate descriptive statistics
- Explore categorical and numerical features
- Document key observations

In [1]:
# Import required libraries

import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

# Display numbers with two decimal places
pd.set_option('display.float_format', '{:.2f}'.format)

In [4]:
# Load dataset

df = pd.read_csv("../data/raw/digital_marketing_dataset_30k.csv")

# Display dataset
df.head()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_holiday (text),is_weekend,is_weekend (text),country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
0,08/04/2023,2023,4,Apr,14,Sat,7,Spring,0,No,1,Yes,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610
1,28/04/2025,2025,4,Apr,18,Mon,12,Spring,0,No,0,No,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086
2,18/12/2024,2024,12,Dec,51,Wed,10,Winter,0,No,0,No,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0
3,26/04/2024,2024,4,Apr,17,Fri,20,Spring,0,No,0,No,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0
4,19/04/2024,2024,4,Apr,16,Fri,22,Spring,0,No,0,No,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160

In [5]:
# Last five records

df.tail()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_holiday (text),is_weekend,is_weekend (text),country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
29995,05/05/2023,2023,5,May,18,Fri,7,Spring,0,No,0,No,Iraq,Tier 1,Fintech_AppX,Brand,Google Search,Search,Conversion,Sales,UGC,C25573,Fintech_AppX_UGC_Conversion_Google Search_May_...,AG776741,UGC_Search_12,AD4737153,Search_V4,79.61,4255,1498,2.84,241,12,1192.40,0
29996,12/10/2025,2025,10,Oct,41,Sun,0,Fall,0,No,1,Yes,Iraq,Tier 1,FMCG_Foodies,Creator,Google Search,Search,Awareness,Video Views,Retargeting,C81668,FMCG_Foodies_Retargeting_Awareness_Google Sear...,AG335235,Retargeting_Search_2,AD3669074,Search_V2,779.14,85192,36862,2.31,5366,1,0.00,8459
29997,29/11/2023,2023,11,Nov,48,Wed,13,Fall,0,No,0,No,KSA,Tier 1,Travel_SkyTrip,Creator,TikTok,In-Feed,Consideration,Traffic,Promo,C76435,Travel_SkyTrip_Promo_Consideration_TikTok_Nov_...,AG440952,Promo_In-Feed_14,AD3415402,In-Feed_V6,115.51,12806,6948,1.84,181,0,0.00,2432
29998,23/03/2025,2025,3,Mar,12,Sun,4,Spring,0,No,1,Yes,KSA,Tier 1,FMCG_Foodies,Brand,Google Display,Display,Awareness,Reach,Educational,C20532,FMCG_Foodies_Educational_Awareness_Google Disp...,AG320612,Educational_Display_43,AD9044768,Display_V2,119.65,23541,14313,1.64,115,0,0.00,0
29999,28/07/2025,2025,7,Jul,31,Mon,10,Summer,0,No,0,No,Iraq,Tier 1,Ecom_ElectroHub,Brand,Google Search,Search,Awareness,Reach,Promo,C97617,Ecom_ElectroHub_Promo_Awareness_Google Search_...,AG648283,Promo_Search_6,AD3936589,Search_V4,475.92,20486,13082,1.57,746,0,0.00,0

In [6]:
# Shape of dataset

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 30000
Columns : 35

In [7]:
# Column names

df.columns

Index(['date', 'year', 'month', 'month_name', 'week', 'day_of_week',
       'post_hour', 'season', 'is_holiday', 'is_holiday (text)', 'is_weekend',
       'is_weekend (text)', 'country', 'market_tier', 'account',
       'account_type', 'platform', 'placement', 'funnel_stage', 'objective',
       'theme', 'campaign_id', 'campaign_name', 'ad_group_id', 'ad_group_name',
       'ad_id', 'ad_name', 'spend', 'impressions', 'reach', 'frequency',
       'clicks', 'conversions', 'revenue', 'video_views'],
      dtype='object')

In [8]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               30000 non-null  object
 1   year               30000 non-null  int64
 2   month              30000 non-null  int64
 3   month_name         30000 non-null  object
 4   week               30000 non-null  int64
 5   day_of_week        30000 non-null  object
 6   post_hour          30000 non-null  int64
 7   season             30000 non-null  object
 8   is_holiday         30000 non-null  int64
 9   is_holiday (text)  30000 non-null  object
 10  is_weekend         30000 non-null  int64
 11  is_weekend (text)  30000 non-null  object
 12  country            30000 non-null  object
 13  market_tier        30000 non-null  object
 14  account            30000 non-null  object
 15  account_type       30000 non-null  object
 16  platform           30000 non-null  object
 17  placement          30000 non-null  object
 18  funnel_stage       30000 non-null  object
 19  objective          30000 non-null  object
 20  theme              30000 non-null  object
 21  campaign_id        30000 non-null  object
 22  campaign_name      30000 non-null  object
 23  ad_group_id        30000 non-null  object
 24  ad_group_name      30000 non-null  object
 25  ad_id              30000 non-null  object
 26  ad_name            30000 non-null  object
 27  spend              30000 non-null  float64
 28  impressions        30000 non-null  int64
 29  reach              30000 non-null  int64
 30  frequency          30000 non-null  float64
 31  clicks             30000 non-null  int64
 32  conversions        30000 non-null  int64
 33  revenue            30000 non-null  float64
 34  video_views        30000 non-null  int64
dtypes: float64(3), int64(11), object(21)
memory usage: 8.0+ MB

In [9]:
# Summary statistics

df.describe()

,year,month,week,post_hour,is_holiday,is_weekend,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
mean,2024.00,6.53,26.46,11.50,0.02,0.28,421.21,56725.45,28648.65,2.07,853.90,10.76,475.71,5176.54
std,0.82,3.45,15.09,6.92,0.12,0.45,463.30,80228.02,41973.09,0.42,1485.99,54.30,2814.17,13486.54
min,2023.00,1.00,1.00,0.00,0.00,0.00,18.84,693.00,277.00,1.11,3.00,0.00,0.00,0.00
25%,2023.00,4.00,13.00,5.00,0.00,0.00,86.15,9432.75,4652.75,1.75,109.00,0.00,0.00,0.00
50%,2024.00,7.00,27.00,11.00,0.00,0.00,229.91,25438.00,12516.00,2.06,311.50,1.00,0.00,0.00
75%,2025.00,10.00,40.00,18.00,0.00,1.00,609.31,69614.50,34562.25,2.37,961.00,3.00,72.35,3245.25
max,2025.00,12.00,52.00,23.00,1.00,1.00,3759.94,1015972.00,682100.00,3.20,30884.00,2701.00,104733.41,218753.00

In [10]:
# Summary statistics including categorical columns

df.describe(include='all')

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_holiday (text),is_weekend,is_weekend (text),country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
count,30000,30000.00,30000.00,30000,30000.00,30000,30000.00,30000,30000.00,30000,30000.00,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
unique,1096,NaN,NaN,12,NaN,7,NaN,4,NaN,2,NaN,2,12,3,7,2,6,11,3,6,8,25548,19192,29496,4041,29956,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,27/04/2025,NaN,NaN,Jul,NaN,Mon,NaN,Spring,NaN,No,NaN,No,KSA,Tier 1,Ecom_FashionCo,Brand,Meta,Feed,Awareness,Reach,Promo,C60988,Ecom_FashionCo_Educational_Consideration_Meta_...,AG656805,Educational_Feed_4,AD4474306,Feed_V2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,45,NaN,NaN,2618,NaN,4363,NaN,7644,NaN,29525,NaN,21486,5578,19862,6636,19053,6867,7324,10110,6032,5421,6,8,3,41,2,865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2024.00,6.53,NaN,26.46,NaN,11.50,NaN,0.02,NaN,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,421.21,56725.45,28648.65,2.07,853.90,10.76,475.71,5176.54
std,NaN,0.82,3.45,NaN,15.09,NaN,6.92,NaN,0.12,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,463.30,80228.02,41973.09,0.42,1485.99,54.30,2814.17,13486.54
min,NaN,2023.00,1.00,NaN,1.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.84,693.00,277.00,1.11,3.00,0.00,0.00,0.00
25%,NaN,2023.00,4.00,NaN,13.00,NaN,5.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.15,9432.75,4652.75,1.75,109.00,0.00,0.00,0.00
50%,NaN,2024.00,7.00,NaN,27.00,NaN,11.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229.91,25438.00,12516.00,2.06,311.50,1.00,0.00,0.00
75%,NaN,2025.00,10.00,NaN,40.00,NaN,18.00,NaN,0.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609.31,69614.50,34562.25,2.37,961.00,3.00,72.35,3245.25
max,NaN,2025.00,12.00,NaN,52.00,NaN,23.00,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3759.94,1015972.00,682100.00,3.20,30884.00,2701.00,104733.41,218753.00

In [11]:
# Missing values

missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [12]:
# Duplicate records

print(f"Duplicate Records: {df.duplicated().sum()}")

Duplicate Records: 0

In [13]:
# Unique values in each column

df.nunique().sort_values()

is_weekend (text)        2
is_holiday               2
is_holiday (text)        2
is_weekend               2
account_type             2
year                     3
funnel_stage             3
market_tier              3
season                   4
objective                6
platform                 6
day_of_week              7
account                  7
theme                    8
placement               11
month_name              12
month                   12
country                 12
post_hour               24
week                    52
ad_name                 99
frequency              210
conversions            405
date                  1096
ad_group_name         4041
clicks                4279
video_views           8607
revenue               8744
campaign_name        19192
reach                21739
spend                24027
impressions          25004
campaign_id          25548
ad_group_id          29496
ad_id                29956
dtype: int64

# Initial Observations

- Dataset contains marketing campaign performance data collected from multiple advertising platforms.
- The dataset consists of both numerical and categorical variables.
- Date-related features enable time-series analysis.
- Campaign hierarchy includes Campaign, Ad Group, and Ad level information.
- Performance metrics include spend, impressions, clicks, conversions, revenue, reach, and video views.
- Marketing KPIs such as CTR, CPC, CPM, CPA, ROAS, ROI, and Conversion Rate are not directly available and will be derived during feature engineering.
- Data quality observations (missing values, duplicates, data types) will be addressed in the next notebook.

## Key Findings

- The dataset contains **30,000 records** and **35 features**, providing sufficient data for comprehensive marketing campaign analysis.

- There are **no missing values** and **no duplicate records**, indicating high-quality data that requires minimal preprocessing.

- The dataset includes **21 categorical columns**, **11 integer columns**, **1 floating-point column**, and **2 boolean indicator columns represented as text**, offering a balanced mix of numerical and categorical features.

- Campaign data spans **2023 to 2025**, enabling trend and seasonality analysis.

- The dataset captures the complete marketing campaign hierarchy:
  - Campaign
  - Ad Group
  - Advertisement

- Performance metrics include:
  - Spend
  - Impressions
  - Reach
  - Frequency
  - Clicks
  - Conversions
  - Revenue
  - Video Views

- Marketing KPIs such as CTR, CPC, CPM, CPA, Conversion Rate, ROAS, and ROI are not directly available and will be engineered during the feature engineering stage.

- The dataset covers multiple advertising platforms including Meta, Google Search, Google Display, TikTok, LinkedIn, and Snapchat, making it suitable for cross-platform campaign analysis.

- Since the dataset is already clean, the next notebook will focus primarily on validating data types, removing redundant columns, and preparing the dataset for feature engineering.