# 🧹 Data Cleaning

## Project Overview

The dataset is already well-structured with no missing values or duplicate records. Therefore, this notebook focuses on validating data quality, standardizing the dataset, optimizing data types, and preparing the data for feature engineering.

## Objectives

- Convert columns to appropriate data types
- Validate numerical columns
- Check categorical consistency
- Remove redundant information
- Standardize column names
- Prepare a clean dataset for feature engineering

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
# Load dataset

df = pd.read_csv("../data/raw/digital_marketing_dataset_30k.csv")

df.head()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_holiday (text),is_weekend,is_weekend (text),country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
0,08/04/2023,2023,4,Apr,14,Sat,7,Spring,0,No,1,Yes,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610
1,28/04/2025,2025,4,Apr,18,Mon,12,Spring,0,No,0,No,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086
2,18/12/2024,2024,12,Dec,51,Wed,10,Winter,0,No,0,No,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0
3,26/04/2024,2024,4,Apr,17,Fri,20,Spring,0,No,0,No,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0
4,19/04/2024,2024,4,Apr,16,Fri,22,Spring,0,No,0,No,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160

In [3]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 30000
Columns : 35

In [4]:
# Check current datatype

df["date"].dtype

dtype('O')

In [5]:
df["date"] = pd.to_datetime(
    df["date"],
    format="%d/%m/%Y",
    dayfirst=True
)

In [6]:
df["date"].dtype

dtype('<M8[ns]')

In [7]:
df.isnull().sum().sum()

0

In [8]:
df.duplicated().sum()

0

In [9]:
numerical_cols = [
    "spend",
    "impressions",
    "reach",
    "frequency",
    "clicks",
    "conversions",
    "revenue",
    "video_views"
]

df[numerical_cols].describe()

,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
mean,421.21,56725.45,28648.65,2.07,853.90,10.76,475.71,5176.54
std,463.30,80228.02,41973.09,0.42,1485.99,54.30,2814.17,13486.54
min,18.84,693.00,277.00,1.11,3.00,0.00,0.00,0.00
25%,86.15,9432.75,4652.75,1.75,109.00,0.00,0.00,0.00
50%,229.91,25438.00,12516.00,2.06,311.50,1.00,0.00,0.00
75%,609.31,69614.50,34562.25,2.37,961.00,3.00,72.35,3245.25
max,3759.94,1015972.00,682100.00,3.20,30884.00,2701.00,104733.41,218753.00

In [10]:
(df[numerical_cols] < 0).sum()

spend          0
impressions    0
reach          0
frequency      0
clicks         0
conversions    0
revenue        0
video_views    0
dtype: int64

In [11]:
pd.crosstab(df["is_holiday"], df["is_holiday (text)"])

is_holiday (text)     No  Yes
is_holiday
0                  29525    0
1                      0  475

In [12]:
pd.crosstab(df["is_weekend"], df["is_weekend (text)"])

is_weekend (text)     No   Yes
is_weekend
0                  21486     0
1                      0  8514

In [13]:
df.drop(
    columns=[
        "is_holiday (text)",
        "is_weekend (text)"
    ],
    inplace=True
)

In [14]:
# Verify updated dataset shape

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 30000
Columns : 33

In [15]:
df.columns = (
    df.columns
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("(", "", regex=False)
      .str.replace(")", "", regex=False)
)

In [16]:
df.columns

Index(['date', 'year', 'month', 'month_name', 'week', 'day_of_week',
       'post_hour', 'season', 'is_holiday', 'is_weekend', 'country',
       'market_tier', 'account', 'account_type', 'platform', 'placement',
       'funnel_stage', 'objective', 'theme', 'campaign_id', 'campaign_name',
       'ad_group_id', 'ad_group_name', 'ad_id', 'ad_name', 'spend',
       'impressions', 'reach', 'frequency', 'clicks', 'conversions', 'revenue',
       'video_views'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           30000 non-null  datetime64[ns]
 1   year           30000 non-null  int64
 2   month          30000 non-null  int64
 3   month_name     30000 non-null  object
 4   week           30000 non-null  int64
 5   day_of_week    30000 non-null  object
 6   post_hour      30000 non-null  int64
 7   season         30000 non-null  object
 8   is_holiday     30000 non-null  int64
 9   is_weekend     30000 non-null  int64
 10  country        30000 non-null  object
 11  market_tier    30000 non-null  object
 12  account        30000 non-null  object
 13  account_type   30000 non-null  object
 14  platform       30000 non-null  object
 15  placement      30000 non-null  object
 16  funnel_stage   30000 non-null  object
 17  objective      30000 non-null  object
 18  theme          30000 non-null  object
 19  campaign_id    30000 non-null  object
 20  campaign_name  30000 non-null  object
 21  ad_group_id    30000 non-null  object
 22  ad_group_name  30000 non-null  object
 23  ad_id          30000 non-null  object
 24  ad_name        30000 non-null  object
 25  spend          30000 non-null  float64
 26  impressions    30000 non-null  int64
 27  reach          30000 non-null  int64
 28  frequency      30000 non-null  float64
 29  clicks         30000 non-null  int64
 30  conversions    30000 non-null  int64
 31  revenue        30000 non-null  float64
 32  video_views    30000 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(11), object(18)
memory usage: 7.6+ MB

In [18]:
df.to_csv("../data/processed/marketing_campaign_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Key Findings

- Converted the `date` column from object to datetime format.
- Verified that the dataset contains no missing values.
- Confirmed that no duplicate records are present.
- Validated that numerical columns contain no negative values.
- Verified consistency between numeric and text versions of holiday and weekend indicators.
- Removed redundant columns:
  - is_holiday (text)
  - is_weekend (text)
- Standardized column names using snake_case.
- Exported the cleaned dataset for feature engineering.