# 📈 Feature Engineering

## Project Overview

This notebook focuses on creating new marketing KPIs and derived features from the cleaned dataset. These engineered features will be used for SQL analysis, Power BI dashboards, and business insights.

## Objectives

- Create marketing performance metrics
- Handle division-by-zero scenarios
- Prepare the dataset for exploratory analysis
- Export the enriched dataset

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
# Load cleaned dataset

df = pd.read_csv("../data/processed/marketing_campaign_cleaned.csv")

df.head()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_weekend,country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views
0,2023-04-08,2023,4,Apr,14,Sat,7,Spring,0,1,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610
1,2025-04-28,2025,4,Apr,18,Mon,12,Spring,0,0,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086
2,2024-12-18,2024,12,Dec,51,Wed,10,Winter,0,0,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0
3,2024-04-26,2024,4,Apr,17,Fri,20,Spring,0,0,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0
4,2024-04-19,2024,4,Apr,16,Fri,22,Spring,0,0,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160

In [3]:
# Click Through Rate

df["ctr"] = np.where(
    df["impressions"] > 0,
    (df["clicks"] / df["impressions"]) * 100,
    0
)

In [4]:
# Cost Per Click

df["cpc"] = np.where(
    df["clicks"] > 0,
    df["spend"] / df["clicks"],
    0
)

In [5]:
# Cost Per Thousand Impressions

df["cpm"] = np.where(
    df["impressions"] > 0,
    (df["spend"] / df["impressions"]) * 1000,
    0
)

In [6]:
# Cost Per Acquisition

df["cpa"] = np.where(
    df["conversions"] > 0,
    df["spend"] / df["conversions"],
    0
)

In [7]:
# Conversion Rate

df["conversion_rate"] = np.where(
    df["clicks"] > 0,
    (df["conversions"] / df["clicks"]) * 100,
    0
)

In [8]:
# Return On Ad Spend

df["roas"] = np.where(
    df["spend"] > 0,
    df["revenue"] / df["spend"],
    0
)

In [9]:
# Return On Investment

df["roi"] = np.where(
    df["spend"] > 0,
    ((df["revenue"] - df["spend"]) / df["spend"]) * 100,
    0
)

In [10]:
# Revenue Per Click

df["revenue_per_click"] = np.where(
    df["clicks"] > 0,
    df["revenue"] / df["clicks"],
    0
)

In [11]:
# Revenue Per Conversion

df["revenue_per_conversion"] = np.where(
    df["conversions"] > 0,
    df["revenue"] / df["conversions"],
    0
)

In [12]:
df.head()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_weekend,country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views,ctr,cpc,cpm,cpa,conversion_rate,roas,roi,revenue_per_click,revenue_per_conversion
0,2023-04-08,2023,4,Apr,14,Sat,7,Spring,0,1,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610,0.83,0.60,5.05,0.00,0.00,0.00,-100.00,0.00,0.00
1,2025-04-28,2025,4,Apr,18,Mon,12,Spring,0,0,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086,0.94,1.28,12.04,0.00,0.00,0.00,-100.00,0.00,0.00
2,2024-12-18,2024,12,Dec,51,Wed,10,Winter,0,0,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0,1.11,0.29,3.26,51.73,0.57,1.86,85.52,0.54,95.96
3,2024-04-26,2024,4,Apr,17,Fri,20,Spring,0,0,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0,0.77,0.66,5.02,0.00,0.00,0.00,-100.00,0.00,0.00
4,2024-04-19,2024,4,Apr,16,Fri,22,Spring,0,0,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160,0.92,0.95,8.75,0.00,0.00,0.00,-100.00,0.00,0.00

In [13]:
kpi_columns = [
    "ctr",
    "cpc",
    "cpm",
    "cpa",
    "conversion_rate",
    "roas",
    "roi",
    "revenue_per_click",
    "revenue_per_conversion"
]

df[kpi_columns].describe()

,ctr,cpc,cpm,cpa,conversion_rate,roas,roi,revenue_per_click,revenue_per_conversion
count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
mean,1.82,1.28,11.67,129.23,0.83,1.08,7.62,0.35,16.19
std,2.02,1.72,9.28,295.06,1.55,3.88,388.21,0.79,36.44
min,0.19,0.07,2.50,0.00,0.00,0.00,-100.00,0.00,0.00
25%,0.73,0.37,5.04,0.00,0.00,0.00,-100.00,0.00,0.00
50%,0.99,0.61,8.18,3.91,0.05,0.00,-100.00,0.00,0.00
75%,1.44,1.10,15.69,81.73,1.16,0.49,-51.09,0.38,15.44
max,13.76,16.70,45.00,3759.94,13.91,92.00,9100.12,11.12,402.54

# Key Findings

- Created 9 key marketing performance indicators (KPIs) from the cleaned dataset.
- Derived metrics measure campaign effectiveness, cost efficiency, profitability, and revenue generation.
- Safely handled division-by-zero scenarios while calculating KPIs.
- The feature-engineered dataset is now ready for Exploratory Data Analysis (EDA), SQL analysis, and Power BI dashboard development.