# 🗄️ Load Data into MySQL

## Project Overview

This notebook prepares the feature-engineered dataset for SQL analysis by loading it into a MySQL database.

The dataset is exported as a CSV file and then imported into MySQL, where SQL queries will be executed to analyze campaign performance and generate business insights.

## Objectives

- Load the feature-engineered dataset
- Verify the dataset structure
- Export the final dataset for MySQL import
- Validate the exported file.

In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
# Load dataset

df = pd.read_csv(
    "../data/processed/marketing_campaign_feature_engineered.csv"
)

df.head()

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_weekend,country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views,ctr,cpc,cpm,cpa,conversion_rate,roas,roi,revenue_per_click,revenue_per_conversion
0,2023-04-08,2023,4,Apr,14,Sat,7,Spring,0,1,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610,0.834144,0.604979,5.046399,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
1,2025-04-28,2025,4,Apr,18,Mon,12,Spring,0,0,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086,0.939856,1.281095,12.040450,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
2,2024-12-18,2024,12,Dec,51,Wed,10,Winter,0,0,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0,1.114061,0.292480,3.258403,51.727143,0.565428,1.855174,85.517413,0.542601,95.962857
3,2024-04-26,2024,4,Apr,17,Fri,20,Spring,0,0,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0,0.765400,0.656024,5.021210,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
4,2024-04-19,2024,4,Apr,16,Fri,22,Spring,0,0,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160,0.918574,0.952203,8.746692,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000

In [3]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.info()

Rows    : 30000
Columns : 42
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    30000 non-null  object
 1   year                    30000 non-null  int64
 2   month                   30000 non-null  int64
 3   month_name              30000 non-null  object
 4   week                    30000 non-null  int64
 5   day_of_week             30000 non-null  object
 6   post_hour               30000 non-null  int64
 7   season                  30000 non-null  object
 8   is_holiday              30000 non-null  int64
 9   is_weekend              30000 non-null  int64
 10  country                 30000 non-null  object
 11  market_tier             30000 non-null  object
 12  account                 30000 non-null  object
 13  account_type            30000 non-null  object
 14  platform                30000 non-null  object
 15  placement               30000 non-null  object
 16  funnel_stage            30000 non-null  object
 17  objective               30000 non-null  object
 18  theme                   30000 non-null  object
 19  campaign_id             30000 non-null  object
 20  campaign_name           30000 non-null  object
 21  ad_group_id             30000 non-null  object
 22  ad_group_name           30000 non-null  object
 23  ad_id                   30000 non-null  object
 24  ad_name                 30000 non-null  object
 25  spend                   30000 non-null  float64
 26  impressions             30000 non-null  int64
 27  reach                   30000 non-null  int64
 28  frequency               30000 non-null  float64
 29  clicks                  30000 non-null  int64
 30  conversions             30000 non-null  int64
 31  revenue                 30000 non-null  float64
 32  video_views             30000 non-null  int64
 33  ctr                     30000 non-null  float64
 34  cpc                     30000 non-null  float64
 35  cpm                     30000 non-null  float64
 36  cpa                     30000 non-null  float64
 37  conversion_rate         30000 non-null  float64
 38  roas                    30000 non-null  float64
 39  roi                     30000 non-null  float64
 40  revenue_per_click       30000 non-null  float64
 41  revenue_per_conversion  30000 non-null  float64
dtypes: float64(12), int64(11), object(19)
memory usage: 9.6+ MB

In [4]:
# Export final dataset for MySQL

output_path = "../data/processed/marketing_campaign_mysql.csv"

df.to_csv(output_path, index=False)

print(f"Dataset exported successfully to:\n{output_path}")

Dataset exported successfully to:
../data/processed/marketing_campaign_mysql.csv

In [5]:
# Read exported file

mysql_df = pd.read_csv(output_path)

print(f"Rows    : {mysql_df.shape[0]}")
print(f"Columns : {mysql_df.shape[1]}")

mysql_df.head()

Rows    : 30000
Columns : 42

,date,year,month,month_name,week,day_of_week,post_hour,season,is_holiday,is_weekend,country,market_tier,account,account_type,platform,placement,funnel_stage,objective,theme,campaign_id,campaign_name,ad_group_id,ad_group_name,ad_id,ad_name,spend,impressions,reach,frequency,clicks,conversions,revenue,video_views,ctr,cpc,cpm,cpa,conversion_rate,roas,roi,revenue_per_click,revenue_per_conversion
0,2023-04-08,2023,4,Apr,14,Sat,7,Spring,0,1,Iraq,Tier 1,Travel_SkyTrip,Brand,TikTok,In-Feed,Awareness,Reach,Product Launch,C30853,Travel_SkyTrip_Product Launch_Awareness_TikTok...,AG412799,Product Launch_In-Feed_6,AD8747890,In-Feed_V1,871.17,172632,77865,2.22,1440,0,0.00,54610,0.834144,0.604979,5.046399,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
1,2025-04-28,2025,4,Apr,18,Mon,12,Spring,0,0,Morocco,Tier 1,FMCG_Foodies,Brand,Meta,Feed,Awareness,Video Views,Seasonal,C49194,FMCG_Foodies_Seasonal_Awareness_Meta_Apr_2025,AG863446,Seasonal_Feed_42,AD2884130,Feed_V9,362.55,30111,15083,2.00,283,0,0.00,8086,0.939856,1.281095,12.040450,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
2,2024-12-18,2024,12,Dec,51,Wed,10,Winter,0,0,United Arab Emirates,Tier 1,Ecom_FashionCo,Brand,Google Display,Display,Conversion,Sales,UGC,C54438,Ecom_FashionCo_UGC_Conversion_Google Display_D...,AG769411,UGC_Display_2,AD5656772,Display_V7,362.09,111125,56453,1.97,1238,7,671.74,0,1.114061,0.292480,3.258403,51.727143,0.565428,1.855174,85.517413,0.542601,95.962857
3,2024-04-26,2024,4,Apr,17,Fri,20,Spring,0,0,KSA,Tier 1,Ecom_ElectroHub,Brand,Snapchat,Stories,Consideration,Traffic,Educational,C60684,Ecom_ElectroHub_Educational_Consideration_Snap...,AG131656,Educational_Stories_49,AD3443678,Stories_V2,54.45,10844,4736,2.29,83,0,0.00,0,0.765400,0.656024,5.021210,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000
4,2024-04-19,2024,4,Apr,16,Fri,22,Spring,0,0,Bahrain,Tier 3,FMCG_Foodies,Brand,Meta,Reels,Awareness,Reach,Retargeting,C57210,FMCG_Foodies_Retargeting_Awareness_Meta_Apr_2024,AG633873,Retargeting_Reels_37,AD8461978,Reels_V8,56.18,6423,3010,2.13,59,0,0.00,1160,0.918574,0.952203,8.746692,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000

# Key Findings

- Successfully loaded the feature-engineered dataset.
- Verified dataset dimensions and column structure.
- Exported the final dataset for MySQL import.
- Validated the exported CSV file to ensure data integrity.
- The dataset is now ready for SQL-based business analysis.